DROP DATABASE IF EXISTS BAMAZON_DB;

CREATE DATABASE BAMAZON_DB;

USE BAMAZON_DB;

CREATE TABLE PRODUCTS
(

    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(500) NOT NULL,
    DEPARTMENT_NAME VARCHAR(500) NOT NULL,
    PRICE FLOAT NOT NULL,
    STOCK_QUANTITY INT NOT NULL -- how much product available

)

-- Populate 10 products

